### PR TITLE
Partial MSVC support, 

### PR DESCRIPTION
**Pull request by jimbo1qaz**
- Add missing return statements.
- Remove dependence on GCC named variadic macros.
- Separate x86 and x64 Windows SDL static libraries.
- Added `qmake` routine to automatically export all .obj symbols into .lib file (rtmidi and famitracker-lib), matching Visual Studio and GCC behavior.
- Renamed apps/famitracker/famitracker.pro → apps/famitracker/famitracker-app.pro.

### CODE REVIEW

**Comment by jimbo1qaz** [comment]
oh god I didn't mean for this to be merged as is. Did you make sure it builds on Linux/Mac without any regressions? The 99999... and 64 return values look *really* shady, but hopefully return values aren't used.

Also you need to reorganize windows deps to put SDL .lib files in a x86 subfolder.

**Comment by christopherpow** [comment]
I made some changes for OSX.

**Comment by christopherpow** [comment]
I can't do Windows at the moment.

**Comment by christopherpow** [comment]
I just changed those to return sane values. They are used only for loading translation DLLs which I don't support.

**Pull request merged**
